### ISSUE TITLE
Proposta

### ISSUE THREAD

**Issue by IgorHalfeld** [alannsiqueira/webschool-box#1]
E aí manolo, beleza, seguinte curti bagarai esse tutorial, me ajudou pakas.
Eu fiz um blog com um brother que tem a intenção de comunitário, qualquer um pode postar...
e queria saber se posso pegar esse conteúdo e colocar lá, queria mais pessoas vissem isso, claro que no final de todo post desse blog tem os devidos direitos entregues, caso você permita que eu use o conteúdo, poderia me passar outros contatos também pra eu colocar ao lado do autor do post, como twitter, linkedin, codepen....

Dá um confere aí
[MyWork's Blog](http://blog.mywork.art.br/)

**Comment by alannsiqueira** [comment]
Claro que pode! e ainda sugiro a melhorar e acrescentar mais coisas. 

Desculpe a demora, mas não recebi um alerta sobre essa issue
